gei_scan:
  I_E: 1.2
  linspace:
    start: 0.01
    stop: 0.4
    num: 10

gie_scan:
  I_E: 1.2
  linspace:
    start: 0.01
    stop: 0.4
    num: 10

gee_scan:
  I_E: 1.2
  linspace:
    start: 0.001
    stop: 0.05
    num: 10

gii_scan:
  I_E: 1.2
  linspace:
    start: 0.01
    stop: 0.4
    num: 10

default_inputs:
  I_E: 0.7
  I_I: 0.7
  noise: 0.8

weights:
  mean_ee: 0.02
  mean_ei: 0.02
  mean_ie: 0.02
  mean_ii: 0.02
  std_ee: 0.0
  std_ei: 0.0
  std_ie: 0.0
  std_ii: 0.0
  p_ee: 0.02
  p_ei: 0.18
  p_ie: 0.04
  p_ii: 0.06
  clamp_min: 0.0

plotting:
  raster:
    start_time: 000.0
    stop_time: 2000.0

base:
  instruments:
    variables: ["V"]
    population_means: true
    all_neurons: false
    neuron_ids: [0, 800]
  dt: 0.1
  T: 5000.0
  seed: 0
  neuron_model: mqif
  N_E: 800
  N_I: 200
  delay_ei: 0.5
  delay_ie: 1.2
  delay_ee: 0.5
  delay_ii: 0.5
  V_init: -65.0
  E_L: -65.0
  E_e: 0.0
  E_i: -80.0
  C_m_E: 1.0
  g_L_E: 0.05
  C_m_I: 1.0
  g_L_I: 0.1
  V_th: -50.0
  V_reset: -65.0
  t_ref_E: 3.0
  t_ref_I: 1.5
  tau_ampa: 2.0
  tau_gaba: 6.5
  mqif_a: [0.02]
  mqif_Vr: [-55.0]
  V_th_heterogeneity_sd: 1.2
  g_L_heterogeneity_sd: 0.15
  C_m_heterogeneity_sd: 0.10
  t_ref_heterogeneity_sd: 0.3
