# https://taskfile.dev

version: '3'

silent: true

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  install:
    desc: Install project dependencies
    cmds:
      - uv sync
      - cd pinglab && uv sync
      - cd cathedral && bun install
      - cd cathedral && bun add cathedral-plugin@file:./plugins/cathedral-plugin/

  execute:
    desc: Execute cathedral with the specified config file
    cmds:
      - touch biblio/.running
      - uv run python {{.CLI_ARGS}}
      - rm biblio/.running

  dev:
    desc: Start the development server
    dir: cathedral
    cmds:
      - bun run dev

  build:
    desc: Build the production assets
    dir: cathedral
    cmds:
      - bun run build

  start:
    desc: Start the production server
    dir: cathedral
    cmds:
      - bun run start

  bg:
    desc: Start the development server in the background
    dir: cathedral
    cmds:
      - pm2 start "bun run dev" --name cathedral

  bg:stop:
    desc: Stop the background development server
    dir: cathedral
    cmds:
      - pm2 delete cathedral
