export const infoText = {
  neuronType: "Select between the LIF and Hodgkin-Huxley models.",
  inputMode: "Choose the input waveform for I_ext.",
  tonic: "Baseline constant input current (arbitrary units).",
  noiseAmp: "Uniform noise added to the input current (arbitrary units).",
  sineAmp: "Amplitude of the sinusoidal modulation (arbitrary units).",
  sineFreq: "Oscillation frequency of the sine input (Hz).",
  pulseAmp: "Amplitude of a single pulse (arbitrary units).",
  pulseStart: "Start time of the single pulse (ms).",
  pulseWidth: "Duration of the single pulse (ms).",
  pulsesAmp: "Amplitude of repeated pulses (arbitrary units).",
  pulsesStart: "Start time for the pulse train (ms).",
  pulsesWidth: "Width of each pulse (ms).",
  pulsesInterval: "Interval between pulses (ms).",
  g_L: "Leak conductance (mS/cm^2).",
  C_m: "Membrane capacitance (uF/cm^2).",
  E_L: "Leak reversal potential (mV).",
  V_init: "Initial membrane potential at t=0 (mV).",
  V_th: "Spike threshold (mV).",
  V_reset: "Reset potential after a spike (mV).",
  dt: "Integration time step (ms).",
  T: "Total simulation duration (ms).",
  hh_g_Na: "Sodium conductance (mS/cm^2).",
  hh_g_K: "Potassium conductance (mS/cm^2).",
  hh_g_L: "Leak conductance (mS/cm^2).",
  hh_C_m: "Membrane capacitance (uF/cm^2).",
  hh_E_Na: "Sodium reversal potential (mV).",
  hh_E_K: "Potassium reversal potential (mV).",
  hh_E_L: "Leak reversal potential (mV).",
  hh_V_init: "Initial membrane potential (mV).",
  mqif_a1: "Quadratic term gain a1 (1/ms).",
  mqif_Vr1: "Quadratic root V_r1 (mV).",
  mqif_g_L: "Leak conductance (mS/cm^2).",
  mqif_C_m: "Membrane capacitance (uF/cm^2).",
  mqif_E_L: "Leak reversal potential (mV).",
  mqif_V_init: "Initial membrane potential (mV).",
  mqif_V_th: "Spike threshold (mV).",
  mqif_V_reset: "Reset potential after a spike (mV).",
};
