plotting:
  raster:
    start_time: 0
    stop_time: 1000
default_inputs:
  I_E: 2
  I_I: 2
  noise: 0
weights:
  clamp_min: 0
  ee:
    p: 0.05
    dist:
      name: normal
      params:
        mean: 0.0202
        std: 0.002
  ei:
    p: 0.04
    dist:
      name: normal
      params:
        mean: 0.0563
        std: 0.002
  ie:
    p: 0.11
    dist:
      name: normal
      params:
        mean: 0.005
        std: 0.002
  ii:
    p: 0.1
    dist:
      name: normal
      params:
        mean: 0.005
        std: 0.002
base:
  neuron_model: mqif
  dt: 0.1
  T: 1000
  seed: 0
  N_E: 800
  N_I: 200
  delay_ei: 0.5
  delay_ie: 1.2
  delay_ee: 0.5
  delay_ii: 0.5
  V_init: -65
  E_L: -65
  E_e: 0
  E_i: -80
  C_m_E: 1
  g_L_E: 0.05
  C_m_I: 1
  g_L_I: 0.1
  V_th: -50
  V_reset: -65
  t_ref_E: 3
  t_ref_I: 1.5
  g_Na: 120
  g_K: 36
  E_Na: 50
  E_K: -77
  tau_ampa: 2
  tau_gaba: 6.5
  mqif_a:
    - 0.02
  mqif_Vr:
    - -55
  mqif_w_a:
    - 0.02
  mqif_w_Vr:
    - -55
  mqif_w_tau:
    - 100
  qif_a: 1
  qif_Vr: -60
  qif_Vt: -45
  izh_a: 0.02
  izh_b: 0.2
  izh_c: -65
  izh_d: 8
  g_L_heterogeneity_sd: 0
  C_m_heterogeneity_sd: 0
  V_th_heterogeneity_sd: 3
  t_ref_heterogeneity_sd: 0