"""snn — the pinglab spiking-network tool.

A thin demolab adapter around the existing pinglab CLI (src/cli/cli.py): each
subcommand runs the CLI (reusing all of its orchestration — wrap, don't rewrite)
into an isolated `_cli/` dir, then re-emits the run as the demolab file set
(config.json + output.json + manifest.json + run.sh) under temp/snn/<cmd>/. The
experiment runner reaches this by *running* the tool, never importing it.
"""

import argparse
import json
import logging
import shlex
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TEMP_DIR = REPO / "temp" / "snn"
PINGLAB_CLI = REPO / "src" / "cli" / "cli.py"


def _run_provenance() -> dict:
    """Git commit + dirty flag + UTC timestamp, so every committed result records
    which code produced it. Degrades gracefully outside a git repo (commit null)."""
    here = Path(__file__).resolve().parent

    def git(*args: str) -> str:
        try:
            r = subprocess.run(["git", *args], cwd=here, capture_output=True, text=True, timeout=5)
            return r.stdout.strip() if r.returncode == 0 else ""
        except Exception:
            return ""

    commit = git("rev-parse", "HEAD")
    return {
        "commit": commit or None,
        # dirty = uncommitted code (src/tools/experiments), not regenerated outputs.
        # `:/` = repo-top magic pathspec so this is correct regardless of git's cwd.
        "dirty": bool(git("status", "--porcelain", "--", ":/src", ":/tools", ":/experiments")) if commit else False,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }


def setup_run_dir(command: str, args: argparse.Namespace) -> tuple[Path, logging.Logger]:
    run_dir = TEMP_DIR / command
    run_dir.mkdir(parents=True, exist_ok=True)

    log_path = run_dir / "output.log"
    logger = logging.getLogger(f"snn.{command}")
    logger.handlers.clear()
    logger.setLevel(logging.INFO)
    formatter = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
    fh = logging.FileHandler(log_path, mode="w")
    fh.setFormatter(formatter)
    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(formatter)
    logger.addHandler(fh)
    logger.addHandler(sh)
    logger.propagate = False

    config = {k: v for k, v in vars(args).items() if k != "func"}
    config["_provenance"] = _run_provenance()
    (run_dir / "config.json").write_text(json.dumps(config, indent=2) + "\n")

    cli_args = [shlex.quote(a) for a in sys.argv[1:]]
    script = Path(sys.argv[0]).resolve()
    try:
        script_rel = script.relative_to(Path.cwd())
    except ValueError:
        script_rel = script
    run_sh = "#!/bin/sh\n"
    run_sh += "# Regenerated by tools/snn/tool.py — reruns this command with the same arguments.\n"
    run_sh += f"exec uv run python {shlex.quote(str(script_rel))} {' '.join(cli_args)}\n"
    (run_dir / "run.sh").write_text(run_sh)
    (run_dir / "run.sh").chmod(0o755)

    return run_dir, logger


def write_output(run_dir: Path, metrics: dict, manifest: dict) -> None:
    missing = [k for k in manifest.get("headline_metrics", []) if k not in metrics]
    if missing:
        raise ValueError(
            f"manifest declares headline_metrics {missing!r} not present in output.json"
        )
    for field in ("headline_figure", "headline_video"):
        name = manifest.get(field)
        if name is None:
            continue
        if not (run_dir / name).exists():
            raise FileNotFoundError(
                f"manifest declares {field}={name!r} but {run_dir / name} does not exist"
            )
    (run_dir / "output.json").write_text(json.dumps(metrics, indent=2) + "\n")
    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


def _run_cli(run_dir: Path, cli_args: list[str], log: logging.Logger) -> dict:
    """Run `src/cli/cli.py sim` into run_dir/_cli/ and return its metrics.json.

    The pinglab CLI does the science + its own provenance; we isolate its raw
    output under _cli/ so the tool's demolab file set stays at the top level.
    """
    cli_dir = run_dir / "_cli"
    cli_dir.mkdir(parents=True, exist_ok=True)
    cmd = ["uv", "run", "python", str(PINGLAB_CLI), "sim", *cli_args,
           "--out-dir", str(cli_dir)]
    log.info("running pinglab CLI: %s", " ".join(cmd))
    subprocess.run(cmd, cwd=REPO, check=True)
    return json.loads((cli_dir / "metrics.json").read_text())


def cmd_sim(args: argparse.Namespace) -> None:
    """One untrained-PING forward pass under uniform-Poisson synthetic-spike drive,
    reporting the population E and I firing rates (Hz). Wraps `cli.py sim`."""
    run_dir, log = setup_run_dir("sim", args)
    cli_args = [
        "--input", "synthetic-spikes", "--model", "ping",
        "--n-hidden", str(args.n_hidden), "--n-in", str(args.n_in),
        "--n-inh", str(args.n_inh),
        "--ei-strength", str(args.ei_strength), "--ei-ratio", str(args.ei_ratio),
        "--w-in", str(args.w_in), "--w-in-sparsity", str(args.w_in_sparsity),
        "--input-rate", str(args.input_rate), "--n-batch", str(args.n_batch),
        "--t-ms", str(args.t_ms), "--dt", str(args.dt), "--seed", str(args.seed),
    ]
    m = _run_cli(run_dir, cli_args, log)
    metrics = {
        "rate_e_hz": float(m["rate_e_hz"]),
        "rate_i_hz": float(m["rate_i_hz"]),
        "n_e": int(args.n_hidden),
        "n_inh": int(args.n_inh),
        "w_ie": float(args.ei_ratio),
    }
    write_output(run_dir, metrics, {"headline_metrics": ["rate_e_hz", "rate_i_hz"]})
    log.info("E=%.2f Hz  I=%.2f Hz", metrics["rate_e_hz"], metrics["rate_i_hz"])


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="snn")
    sub = parser.add_subparsers(dest="command", required=True)

    sim = sub.add_parser("sim", help="Untrained-PING forward pass → population E/I rates")
    sim.add_argument("--n-hidden", type=int, default=1024, help="Excitatory pool size N_E")
    sim.add_argument("--n-in", type=int, default=784, help="Input channels")
    sim.add_argument("--n-inh", type=int, default=256, help="Inhibitory pool size N_I")
    sim.add_argument("--ei-strength", type=float, default=1.0, help="Sets W_EI mean")
    sim.add_argument("--ei-ratio", type=float, default=2.0, help="Sets the per-synapse W_IE mean")
    sim.add_argument("--w-in", type=float, default=1.2, help="Input weight mean")
    sim.add_argument("--w-in-sparsity", type=float, default=0.95, help="Input weight sparsity")
    sim.add_argument("--input-rate", type=float, default=25.0, help="Uniform Poisson input rate (Hz)")
    sim.add_argument("--n-batch", type=int, default=4, help="Trials in the batch")
    sim.add_argument("--t-ms", type=float, default=200.0, help="Simulation duration (ms)")
    sim.add_argument("--dt", type=float, default=0.1, help="Integration timestep (ms)")
    sim.add_argument("--seed", type=int, default=42, help="Random seed")
    sim.set_defaults(func=cmd_sim)

    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
