"""snn — the pinglab spiking-network tool.

A thin demolab adapter around the existing pinglab CLI (src/cli/cli.py). The
CLI has a large, research-grade flag surface (~40 options across sim / train /
dump-weights), and the experiments drive it in many different combinations, so
the tool is a **provenance-wrapping passthrough** rather than a typed wrapper:

    snn <subcommand> [any cli.py args...]

It forwards every argument verbatim to `cli.py <subcommand>`, stamps the run
with git provenance, and emits the demolab file set (config.json + run.sh, plus
output.json/manifest.json when the CLI produced a metrics.json) alongside the
CLI's own output. Experiments reach this by *running* it, never importing it —
they pass the same flags they would have passed to cli.py, and read the CLI
artifacts (metrics.json, *.npz, weights.pth) back from --out-dir.

Wrap, don't rewrite: all of the science + the CLI's own provenance stays in
cli.py; the tool only records "this run happened, with this code version".
"""

import argparse
import json
import logging
import shlex
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TEMP_DIR = REPO / "temp" / "snn"
PINGLAB_CLI = REPO / "src" / "cli" / "cli.py"

# The cli.py subcommands the tool is allowed to forward to. Kept explicit so a
# typo (`snn trian ...`) fails loudly instead of shelling out to a bad command.
SUBCOMMANDS = ("sim", "train", "dump-weights")


def _run_provenance() -> dict:
    """Git commit + dirty flag + UTC timestamp, so every committed result records
    which code produced it. Degrades gracefully outside a git repo (commit null)."""
    here = Path(__file__).resolve().parent

    def git(*args: str) -> str:
        try:
            r = subprocess.run(["git", *args], cwd=here, capture_output=True, text=True, timeout=5)
            return r.stdout.strip() if r.returncode == 0 else ""
        except Exception:
            return ""

    commit = git("rev-parse", "HEAD")
    return {
        "commit": commit or None,
        # dirty = uncommitted code (src/tools/experiments), not regenerated outputs.
        # `:/` = repo-top magic pathspec so this is correct regardless of git's cwd.
        "dirty": bool(git("status", "--porcelain", "--", ":/src", ":/tools", ":/experiments")) if commit else False,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }


def setup_run_dir(command: str, cli_args: list[str]) -> tuple[Path, logging.Logger]:
    """Prepare temp/snn/<command>/ with config.json (the forwarded args + provenance),
    run.sh (re-runs this exact invocation), and a logger writing output.log."""
    run_dir = TEMP_DIR / command
    run_dir.mkdir(parents=True, exist_ok=True)

    log_path = run_dir / "output.log"
    logger = logging.getLogger(f"snn.{command}")
    logger.handlers.clear()
    logger.setLevel(logging.INFO)
    formatter = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
    fh = logging.FileHandler(log_path, mode="w")
    fh.setFormatter(formatter)
    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(formatter)
    logger.addHandler(fh)
    logger.addHandler(sh)
    logger.propagate = False

    config = {
        "subcommand": command,
        "cli_args": list(cli_args),
        "_provenance": _run_provenance(),
    }
    (run_dir / "config.json").write_text(json.dumps(config, indent=2) + "\n")

    cli_argv = [shlex.quote(a) for a in sys.argv[1:]]
    script = Path(sys.argv[0]).resolve()
    try:
        script_rel = script.relative_to(Path.cwd())
    except ValueError:
        script_rel = script
    run_sh = "#!/bin/sh\n"
    run_sh += "# Regenerated by tools/snn/tool.py — reruns this command with the same arguments.\n"
    run_sh += f"exec uv run python {shlex.quote(str(script_rel))} {' '.join(cli_argv)}\n"
    (run_dir / "run.sh").write_text(run_sh)
    (run_dir / "run.sh").chmod(0o755)

    return run_dir, logger


def write_output(run_dir: Path, metrics: dict, manifest: dict) -> None:
    """Emit output.json + manifest.json, validating the manifest can't lie: every
    declared headline metric must be present, every declared figure/video must exist."""
    missing = [k for k in manifest.get("headline_metrics", []) if k not in metrics]
    if missing:
        raise ValueError(
            f"manifest declares headline_metrics {missing!r} not present in output.json"
        )
    for field in ("headline_figure", "headline_video"):
        name = manifest.get(field)
        if name is None:
            continue
        if not (run_dir / name).exists():
            raise FileNotFoundError(
                f"manifest declares {field}={name!r} but {run_dir / name} does not exist"
            )
    (run_dir / "output.json").write_text(json.dumps(metrics, indent=2) + "\n")
    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


def _cli_out_dir(cli_args: list[str], default: Path) -> Path:
    """The --out-dir the caller passed to the CLI, or `default` if none. The CLI
    writes metrics.json / *.npz / weights.pth there, and the experiment reads them
    back from the same place."""
    for i, a in enumerate(cli_args):
        if a == "--out-dir" and i + 1 < len(cli_args):
            return Path(cli_args[i + 1])
        if a.startswith("--out-dir="):
            return Path(a.split("=", 1)[1])
    return default


def run(command: str, cli_args: list[str]) -> Path:
    """Forward `cli.py <command> <cli_args>` and mirror any metrics.json to the
    demolab output.json. Returns the CLI's output directory so a caller (or an
    experiment via subprocess) can read the run's artifacts.

    If the caller supplied --out-dir it is honoured (sweeps write each point to
    its own dir); otherwise the CLI writes into temp/snn/<command>/_cli/.
    """
    run_dir, log = setup_run_dir(command, cli_args)
    out_dir = _cli_out_dir(cli_args, run_dir / "_cli")
    out_dir.mkdir(parents=True, exist_ok=True)

    forwarded = list(cli_args)
    if not any(a == "--out-dir" or a.startswith("--out-dir=") for a in cli_args):
        forwarded += ["--out-dir", str(out_dir)]

    cmd = ["uv", "run", "python", str(PINGLAB_CLI), command, *forwarded]
    log.info("running pinglab CLI: %s", " ".join(cmd))
    subprocess.run(cmd, cwd=REPO, check=True)

    metrics_path = out_dir / "metrics.json"
    if metrics_path.exists():
        metrics = json.loads(metrics_path.read_text())
        # A passthrough run declares no headline metric of its own — the CLI's
        # metrics.json is mirrored wholesale so downstream tooling sees output.json.
        write_output(run_dir, metrics, {"headline_metrics": []})
        log.info("mirrored %d CLI metric(s) to output.json", len(metrics))
    return out_dir


def build_parser() -> argparse.ArgumentParser:
    """A deliberately thin parser: it validates the subcommand and captures the
    rest verbatim for passthrough to cli.py (parse_known_args in main())."""
    parser = argparse.ArgumentParser(
        prog="snn",
        description="Provenance-wrapping passthrough to the pinglab CLI.",
    )
    parser.add_argument("command", choices=SUBCOMMANDS, help="cli.py subcommand to run")
    return parser


def main() -> None:
    args, cli_args = build_parser().parse_known_args()
    run(args.command, cli_args)


if __name__ == "__main__":
    main()
