#!/usr/bin/env sh
# Reproducer for exp063 — regenerates this record from a clean run.
# Auto-generated by helpers/provenance.write_run_sh (RULES §4.7); do not edit.
cd "$(git rev-parse --show-toplevel)"
exec uv run python experiments/exp063.py
