plotting:
  raster:
    start_time: 0.0
    stop_time: 1000.0

scan:
  mean_ei:
    start: 0.01
    stop: 0.05
    num: 20
  std_ei:
    start: 0.0
    stop: 0.08
    num: 20
  mean_ie:
    start: 0.0
    stop: 0.12
    num: 10
  std_ie:
    start: 0.0
    stop: 0.3
    num: 10
  mean_ee:
    start: 0.0
    stop: 0.12
    num: 10
  std_ee:
    start: 0.0
    stop: 0.3
    num: 10
  mean_ii:
    start: 0.0
    stop: 0.12
    num: 10
  std_ii:
    start: 0.0
    stop: 0.3
    num: 10

default_inputs:
  I_E: 0.7
  I_I: 0.7
  noise: 0.5

rate_match:
  I_E:
    start: 0.2
    stop: 2.0
    num: 21
  window_ms:
    start: 100.0
    stop: 300.0
  sim_T: 300.0
  target_rate_e: 20.0

weights:
  mean_ee: 0.02
  mean_ei: 0.015
  mean_ie: 0.015
  mean_ii: 0.02
  std_ee: 0.0
  std_ei: 0.0
  std_ie: 0.0
  std_ii: 0.0
  p_ee: 0.02
  p_ei: 0.18
  p_ie: 0.04
  p_ii: 0.06
  clamp_min: 0.0

base:
  neuron_model: mqif
  dt: 0.1
  T: 1000.0
  seed: 0

  N_E: 800
  N_I: 200

  delay_ei: 0.5
  delay_ie: 1.2
  delay_ee: 0.5
  delay_ii: 0.5

  V_init: -65.0
  E_L: -65.0
  E_e: 0.0
  E_i: -80.0
  C_m_E: 1.0
  g_L_E: 0.05
  C_m_I: 1.0
  g_L_I: 0.1
  V_th: -50.0
  V_reset: -65.0
  t_ref_E: 3.0
  t_ref_I: 1.5

  mqif_a: [0.02]
  mqif_Vr: [-55.0]

  g_Na: 120.0
  g_K: 36.0
  E_Na: 50.0
  E_K: -77.0

  tau_ampa: 2.0
  tau_gaba: 6.5

  V_th_heterogeneity_sd: 1.2
  g_L_heterogeneity_sd: 0.15
  C_m_heterogeneity_sd: 0.1
  t_ref_heterogeneity_sd: 0.3
