"""Canonical operating point for the gamma-gated-sparsity collection.

SINGLE SOURCE OF TRUTH for the inhibitory time constant that defines "the loop
is in gamma" and the gamma frequency/period that follow from it. Every notebook
that needs the collection's canonical rhythm — the mean-field analysis (nb033),
the streaming reference lines (nb048), and the training hub (nb022) — imports
from here instead of hardcoding a value, so moving the operating point is a
one-line edit followed by a re-run, not a scattered grep-and-replace.

Why 6 ms (and why it is still biophysical):
    τ_GABA sets the E–I gamma frequency f_γ. At τ_GABA = 9 ms, nb041 measures
    f_γ ≈ 36 Hz (3 seeds) — gamma, but the low edge of the band. At τ_GABA = 6 ms
    the loop sits centrally in gamma at f_γ ≈ 44 Hz.
        6 ms is NOT sub-biophysical: gamma is generated by fast perisomatic GABA_A
        synapses from PV+ basket cells, whose IPSC decay is ~5–8 ms (Bartos, Vida &
        Jonas 2007, Nat Rev Neurosci 8:45, doi:10.1038/nrn2044) — faster than the
        ~9–12 ms of generic dendritic GABA_A (Börgers 9 ms; Buzsaki & Wang 8–12 ms,
        which the models.py library default keeps). 6 ms is the fast-PV value for the
        exact synapse type that drives gamma, so it gives central gamma AND stays
        biophysical. (The manuscript's old "25 Hz" was the mean-field prediction
        leaking in; it was never the measured spiking value at any τ_GABA.)

Where F_GAMMA_HZ comes from:
    It is the MEASURED spiking gamma frequency at TAU_GABA_GAMMA_MS, taken as the
    3-seed mean from nb041's numbers.json (canonical PING, f_γ-vs-τ_GABA sweep).
    It is NOT a mean-field number and NOT a guess. If nb041 is re-run and the
    measurement shifts, update F_GAMMA_HZ here (and only here).

    nb041 3-seed means (for reference / re-derivation):
        τ_GABA = 4.5 ms → f_γ ≈ 53.8 Hz   (T_γ ≈ 18.6 ms)
        τ_GABA = 6.0 ms → f_γ ≈ 44.0 Hz   (T_γ ≈ 22.8 ms)   ← canonical
        τ_GABA = 9.0 ms → f_γ ≈ 36.3 Hz   (T_γ ≈ 27.5 ms)
        τ_GABA = 12  ms → f_γ ≈ 28.0 Hz   (T_γ ≈ 35.8 ms)
"""

from __future__ import annotations

# Canonical inhibitory (GABA) synaptic decay — the collection's operating point.
# Passed to the CLI as --tau-gaba when training every non-sweep cell (nb022).
TAU_GABA_GAMMA_MS: float = 6.0

# Measured spiking gamma frequency at TAU_GABA_GAMMA_MS (nb041, 3-seed mean).
# Re-derive from nb041 if the operating point or the measurement changes.
F_GAMMA_HZ: float = 43.95

# Gamma period. Everything downstream (sub-cycle floor 0.4·T_γ, streaming
# reference lines, "one gamma cycle" arithmetic) derives from this.
T_GAMMA_MS: float = 1000.0 / F_GAMMA_HZ  # ≈ 22.8 ms

# ── NOT the operating point — the library fallback (mirror of models.py) ─────
# Mirror of src/cli/models.py's module default `tau_gaba = 9.0` (the literature
# biophysical value). It is what a cell ran at if trained WITHOUT an explicit
# --tau-gaba, so it is the correct fallback for "cfg.get('tau_gaba_ms') or …"
# when a loaded cell's config predates that field. Distinct from
# TAU_GABA_GAMMA_MS: that is "what the collection trains at" (6 ms), this is
# "what the CLI falls back to" (9 ms). Notebooks can't import models (the CLI
# boundary), so keep this in sync by hand if the models.py default changes.
MODELS_DEFAULT_TAU_GABA_MS: float = 9.0
