#import "/.demolab/lib.typ": cite, reference-list

#let meta = (
  title: "The Functional Role of PING: mapping the space",
  date: "2026-07-12",
  description: "An exhaustive, DOI-verified, recall-measured corpus of papers in which the PING mechanism (gamma from reciprocal pyramidal–interneuron interaction) is explicitly the vehicle for a functional claim. Built by four decorrelated capture channels, membership decided by a consistent two-stage judge, completeness estimated by capture–recapture.",
  collection: "miscellaneous",
  status: "final",
)

// Every headline number is interpolated from the committed record, never hand-typed:
// a re-run of the search regenerates artifacts/data/ar016/ and this article follows.
#let n = json("/artifacts/data/ar016/numbers.json")
#let refs = json("/artifacts/data/ar016/references.json")
#let ms = n.estimates.chapman_memory_x_search
#let tlo = n.honest_readout.true_size_range.at(0)
#let thi = n.honest_readout.true_size_range.at(1)
#let rlo = n.honest_readout.recall_range_pct.at(0)
#let rhi = n.honest_readout.recall_range_pct.at(1)
#let yc = n.yield_curve
#let pv = n.provenance
#let fn = n.funnel
#let ax = n.axis_distribution
#let sc = n.scout
#let hl = n.hallucination
#let cv = json("/artifacts/data/ar016/corpus_view.json")
#let crit = json("/artifacts/data/ar016/critiques.json")

// function-axis display order + human labels
#let axis-order = (
  ("communication-coherence-routing", "Communication-through-coherence, routing & gating"),
  ("attention-selection", "Attention & stimulus selection"),
  ("stimulus-competition", "Stimulus & biased competition"),
  ("coincidence-gain-window", "Coincidence detection, gain & the temporal window"),
  ("phase-coding-timing", "Phase coding & spike timing"),
  ("binding-synchrony", "Binding by synchrony"),
  ("causal-optogenetic-performance", "Causal / optogenetic PV–gamma & circuit performance"),
  ("mechanism-review", "Reviews & theory (mechanism → function)"),
)

#let body = [
  == Abstract

  This article is a _corpus_, not a review. It is an attempt at an exhaustive, auditable paper list for one narrow question, leaving the synthesis, the open debates, and the gaps to a later pass. The question:

  #quote(block: true)[
    In which papers is the PING mechanism explicitly the vehicle for a functional claim?
  ]

  PING here means gamma generated by the reciprocal pyramidal↔interneuron loop with its characteristic excitatory–inhibitory timing. A paper is in the corpus only if it both invokes that mechanism as the generator of the rhythm _and_ argues that a cognitive or computational function follows from it: attention, stimulus selection, communication-through-coherence, gain control and coincidence windows, phase coding, or binding. Papers where gamma merely _correlates_ with a function, or where the mechanism is studied with no functional claim, are out; so are critiques that attack a function without naming the mechanism, though the major ones are collected in the appendix so the eventual review can engage them. The scope was frozen and git tagged (`freeze-ar016-v1`) before any measured run, so the recall figure below is valid: the completeness estimate compares samples of one fixed population, which a scope that drifted mid-run would destroy.

  #table(
    columns: (auto, auto),
    align: (left, left),
    stroke: 0.5pt + luma(200),
    [*Papers in the corpus*], [#n.corpus_in_hand, every DOI verified],
    [*Estimated true size*], [≈ #tlo–#thi (two-source Chapman #ms.N, 95% CI #ms.ci95.at(0)–#ms.ci95.at(1))],
    [*Estimated recall*], [≈ #rlo–#rhi %],
    [*Channels*], [memory · keyword-search · citation-graph · embedding],
    [*Membership authority*], [one two-stage judge (wide-net → confirm), consistent across channels],
    [*Coverage caveats*],
    [keyless (no Semantic Scholar / PubMed); single judge per paper; OpenAlex abstract gaps on seminal papers],
  )

  The estimate is a range, not a point. Completeness is measured by _capture–recapture_ (the Lincoln–Petersen / Chapman estimator): when two channels independently sample one fixed population, the size of their overlap implies how many papers both missed, and so the true size $hat(N)$. Computed over the three channel-pairs that overlap, it yields three estimates, and they disagree: #n.estimates.chapman_memory_x_search.N (memory × search), #n.estimates.chapman_search_x_citation.N (search × citation), and #n.estimates.chapman_memory_x_citation.N (memory × citation). The disagreement is expected rather than anomalous: the channels have heterogeneous catchability (memory reaches the old and seminal, search the recent and well-indexed), which violates the independence the estimator assumes. No single $hat(N)$ is reliable, so we report the band #tlo–#thi and a recall of #rlo–#rhi % rather than a point value.

  == Methods

  The model can estimate the size of a literature (it can tell hundreds from thousands) and judge whether a specific paper is in scope. Its memory is also a recall channel: unreliable in a single readout, where it is lossy and confabulates at the margin, but usable once multiplexed across many decorrelated passes and filtered through DOI verification. Recall is gathered from four channels (memory among them), membership is decided by judgment, and completeness is estimated statistically. The procedure, in order:

  + *Refine and scout the question, before anything is frozen.* The raw interest ("the big questions about PING") is too broad to search, so it is narrowed conversationally: the model reflects the corpus size back from memory (gamma broadly is thousands of papers; the mechanism-carries-function slice is hundreds), weighs narrowing and widening axes by their size, and converges on #sc.anchors anchors with explicit in/out boundaries, targeting #sc.target_range.at(0)–#sc.target_range.at(1). A cheap scout pass then probes live database counts to confirm the slice is exhaustible and expose traps: the mechanism core returns #sc.probes.PING_gamma_oscillation–#sc.probes.pyramidal_interneuron_network_gamma hits against the "communication through coherence" balloon (#sc.probes.communication_through_coherence hits) the scope must exclude, and the coincidence/gain axis is nearly invisible to keywords (#sc.probes.gamma_interneuron_coincidence hits), needing concept-level queries later. It also flags collisions like "PING" naming a network tool. The result is the scope proposal, estimated at #sc.frozen_estimate.at(0)–#sc.frozen_estimate.at(1), which is then frozen.

  + *Freeze the scope.* The inclusion rubric is fixed and git tagged (`freeze-ar016-v1`) before any measured run, so both capture samples target one fixed population and the recall figure is meaningful.

  + *Gather recall from four orthogonal channels,* chosen to fail on different papers so their union covers what any one misses:
    - *Memory / weights:* 20 decorrelated elicitation passes (per-lab, per-function-axis, per-decade), each in its own context, unioned. This channel is the knowledge baked into the model's trained weights. Covers the old, seminal, abstract-less stratum.
    - *Keyword search:* a deep OpenAlex full-text sweep across the frozen synonym ring (the fixed set of the concept's synonyms and near-terms, agreed at scope-freeze), deliberately high-recall. Covers the recent, well-indexed stratum.
    - *Citation graph:* the backward references and forward citers of the found set, scored by how many of the corpus each candidate connects to. Covers the well-connected stratum, independent of words and of memory.
    - *Embedding:* nearest neighbours of the strongest seeds in SPECTER (a document-embedding model, served by Semantic Scholar, that places papers by learned content similarity), independent of shared words, citations, and authorship.

  + *Verify every candidate DOI against Crossref.* An unresolvable DOI is treated as a hallucination and discarded, so nothing enters the corpus that cannot be resolved to a real paper.

  + *Judge membership with one consistent two-stage judge:* a wide-net first pass, then a strict confirming pass against the frozen rubric, so the in/out boundary is one authority applied uniformly. Membership is _not_ decided by any keyword filter. An earlier attempt to do so failed, because a filter strict enough to exclude the broad "gamma and attention" literature also excludes the function-forward canonical papers whose abstracts never say "interneuron".

  + *Estimate completeness by capture–recapture.* Lincoln–Petersen / Chapman over the single judged population, treating each channel as an independent capture, gives the true-size band and the recall figure.

  === Hallucination and verification

  Because a language model generates the memory channel, fabricated references are the obvious failure mode. Every model-proposed reference passes a two-layer DOI check: each generating pass self-verifies against Crossref and drops what will not resolve, then an independent re-check resolves the deduplicated union again. In a controlled pilot where the model gave author, year, and title (not DOIs) and the resolver did the lookup, all #hl.pilot_real of #hl.pilot_recalled recalled papers were real, resolvable works. In the full harvest the #str(20) memory passes returned #hl.memory_raw_returns candidates, deduplicated to #hl.memory_unique_dois references, of which #hl.memory_unresolvable failed to resolve at the re-check.

  The caveat is that DOI-resolution catches an _invented identifier_ but not a _valid DOI attached to the wrong paper_. That residual is real: a later audit removed #hl.junk_doi_removed reference whose DOI resolved only to a journal, and corrected #hl.metadata_corrected records with valid DOIs but corrupt third-party metadata (a prostate-cancer note, a Japanese architecture paper). Resolution is necessary but not sufficient; a Crossref-versus-OpenAlex cross-check catches the rest. One such entry reached the list and was removed.

  == Results

  The four channels surfaced #fn.distinct_papers_judged distinct candidate papers, every one put through the same membership judge. #fn.accepted_in_scope were accepted and #fn.rejected rejected, an acceptance rate of #fn.acceptance_pct %. Most rejected candidates are gamma-and-cognition papers that do not make the mechanism-_carries_-function argument.

  #table(
    columns: (auto, auto),
    align: (left, right),
    stroke: 0.5pt + luma(200),
    [*Candidates judged (search + memory union)*], [#fn.by_stage.search_plus_memory_union],
    [*Candidates judged (citation graph)*], [#fn.by_stage.citation_candidates],
    [*Candidates judged (embedding)*], [#fn.by_stage.embedding_candidates],
    [*Total distinct papers judged*], [#fn.distinct_papers_judged],
    [*Accepted into the corpus*], [#fn.accepted_in_scope (#fn.acceptance_pct %)],
    [*Rejected*], [#fn.rejected],
  )

  === Provenance

  The corpus is the union of complementary channels; no single one would have produced it:

  #table(
    columns: (auto, auto),
    align: (left, right),
    stroke: 0.5pt + luma(200),
    [*Found by memory only*], [#pv.memory_only],
    [*Found by search only*], [#pv.search_only],
    [*Found by memory and search*], [#pv.memory_and_search],
    [*Found by citation graph only*], [#pv.citation_only],
    [*Total*], [#n.corpus_in_hand],
  )

  Only #pv.memory_and_search of the #n.corpus_in_hand papers were caught by both memory and keyword search. The low overlap reflects the channels' complementarity, and is why four were needed rather than one.

  === Saturation

  The stopping point rests on the marginal-yield curve rather than a target count. Each successive channel returned fewer new in-scope papers:

  #table(
    columns: (auto, auto, auto),
    align: (left, right, right),
    stroke: 0.5pt + luma(200),
    [*Channel*], [*New in-scope*], [*Candidates screened*],
    [memory], [#yc.memory], [n/a],
    [keyword search], [+#yc.search_new], [1552],
    [citation graph], [+#yc.citation_new], [#fn.by_stage.citation_candidates],
    [embedding (SPECTER)], [+#yc.embedding_new], [#fn.by_stage.embedding_candidates],
  )

  The yield fell from #yc.memory to +#yc.search_new to +#yc.citation_new to +#yc.embedding_new. The final channel (orthogonal, abstract-rich, centred on the hundred strongest seeds) screened #fn.by_stage.embedding_candidates semantic neighbours and added nothing. This is a saturation signal rather than a proof: falling returns together with a null from an orthogonal channel. It should be discounted somewhat, since SPECTER is recency-biased and its null is strongest for recent work; but the citation channel already covered the older literature, so the remaining un-caught set is probably small.

  === Distribution by function axis

  Every paper is tagged with the one function its mechanism-to-function argument chiefly serves, from a fixed set of eight. The distribution is the first-order map of the field:

  #table(
    columns: (auto, auto),
    align: (left, right),
    stroke: 0.5pt + luma(200),
    ..axis-order.map(((k, label)) => (label, [#ax.at(k, default: 0)])).flatten(),
    [*Total*], [#n.corpus_in_hand],
  )

  Communication-through-coherence and routing is the largest axis (#ax.at("communication-coherence-routing", default: 0)): the recurring claim is that the E–I gamma rhythm gates which signals pass between areas. The causal / optogenetic cluster (#ax.at("causal-optogenetic-performance", default: 0)) is a sizeable group of its own, reflecting a shift from correlating gamma with function to manipulating PV interneurons and measuring the effect. The full annotated list, grouped by axis with a one-line rationale per paper, is the bibliography below.

  == Discussion

  This is a DOI-verified corpus of #n.corpus_in_hand papers, with a _measured_ recall of roughly #rlo–#rhi %, and a recorded reason for each paper's inclusion. It is not complete. The tail of a semantic corpus is expensive (papers in no index, mis-tagged, or obscure cost more per paper than the bulk did), and the capture–recapture band (#tlo–#thi) is itself uncertain because the channels are heterogeneous. The most-cited references of the corpus are foundational papers that are purely mechanism (how gamma is generated) or purely function (attention modulates gamma), each satisfying only half the "mechanism carries function" test; this is why the citation graph returned many candidates but few members. The scope is restrictive, and the set it defines is small.

  The strict scope excludes one class of paper by construction: the _critique_. Papers that question a functional claim (does synchrony bind? does gamma carry a usable code?) argue at the level of spike timing or coding in general, without naming the pyramidal↔interneuron loop as the generator, so they fail the mechanism-as-vehicle test. The judge rejected the canonical skeptics it saw (Shadlen & Movshon's _Synchrony Unbound_ and both Ray & Maunsell papers), and the recall channels did not reach the others (Thiele & Stoner, Palanca & DeAngelis, Merker), since the scope does not target them. This is consistent for a corpus but a limitation for a review, which should not omit the critical literature. The major critiques are listed in the appendix, outside the corpus, for that later pass.

  The run did not support the assumption that a language model is a poor recall channel. Multiplexed across #str(20) decorrelated passes and filtered through DOI verification, memory was the largest single channel: #(pv.memory_only + pv.memory_and_search) of the #n.corpus_in_hand in-scope papers, #pv.memory_only of them found by memory alone, with low fabrication (#hl.pilot_real of #hl.pilot_recalled real in the controlled pilot, #hl.memory_unresolvable of #hl.memory_unique_dois unresolvable in the full harvest). What made memory usable was decorrelation and verification, not restricting its use.

  == Next steps

  The corpus is the input to the review, not the review. The obvious continuations: (1) a second, independent judge pass to turn the single-judge boundary into a voted one and tighten precision; (2) one more orthogonal recall channel where a key exists (PubMed for the biomedical silo, or author-complete feeds for the core labs), expected, from the yield curve, to add only single digits; (3) the synthesis itself, reading down each axis below to map which mechanistic claims are contested and where the gaps are. Scope reopens only under a new freeze tag; questions that surfaced during the build are logged, not silently acted on.

  == The corpus: annotated bibliography by function axis

  All #n.corpus_in_hand papers, grouped by primary function axis and sorted by year, each with a one-sentence statement of how the E–I/PING gamma mechanism carries its functional claim and a tag for the channel that found it (_m_ memory · _s_ search · _m+s_ both · _c_ citation).

  #context {
    let web = target() == "html"
    for (key, label) in axis-order {
      let items = cv.filter(r => r.axis == key)
      heading(level: 3, label + " (" + str(items.len()) + ")")
      if web {
        // reuse the house citation style: ol.refs + .doi from .demolab/style.css
        html.elem("ol", attrs: (class: "refs"), {
          for r in items {
            html.elem("li", {
              html.elem("strong", r.byline)
              ". " + r.title + ". "
              if r.venue != "" {
                html.elem("em", r.venue)
                ". "
              }
              html.elem(
                "a",
                attrs: (class: "doi", href: "https://doi.org/" + r.doi, target: "_blank", rel: "noopener"),
                "doi:" + r.doi,
              )
              html.elem("br")
              r.rationale + " "
              html.elem("span", attrs: (class: "doi"), "[" + r.channel + "]")
            })
          }
        })
      } else {
        enum(..items.map(r => [
          #strong(r.byline). #r.title.#if r.venue != "" [ #emph(r.venue).] #text(fill: luma(120))[doi:#r.doi] \
          #r.rationale #text(fill: luma(140))[\[#r.channel\]]
        ]))
      }
    }
  }

  == Appendix: adjacent critiques (not corpus members)

  These are the major skeptical papers on gamma/synchrony function. They are _not_ in the frozen corpus and are excluded from every count and recall figure above: each questions a functional claim without naming the E–I/PING loop as the generator, so it fails the mechanism-as-vehicle test. They are recorded here for the later review. The disposition tag marks whether the build surfaced and rejected the paper, or never reached it.

  #context {
    let web = target() == "html"
    if web {
      html.elem("ol", attrs: (class: "refs"), {
        for r in crit {
          html.elem("li", {
            html.elem("strong", r.byline)
            ". " + r.title + ". "
            html.elem("em", r.venue)
            ". "
            html.elem("a", attrs: (class: "doi", href: "https://doi.org/" + r.doi, target: "_blank", rel: "noopener"), "doi:" + r.doi)
            html.elem("span", attrs: (class: "doi"), " (" + r.disposition + ")")
          })
        }
      })
    } else {
      enum(..crit.map(r => [
        #strong(r.byline). #r.title. #emph(r.venue). #text(fill: luma(120))[doi:#r.doi] #text(fill: luma(140))[(#r.disposition)]
      ]))
    }
  }
]
