#import "/.demolab/lib.typ": cite, reference-list

#let meta = (
  title: "The Functional Role of PING — a Measured Corpus",
  date: "2026-07-12",
  description: "An exhaustive, DOI-verified, recall-measured corpus of papers in which the PING mechanism (gamma from reciprocal pyramidal–interneuron interaction) is explicitly the vehicle for a functional claim. Built by four decorrelated capture channels, membership decided by a consistent two-stage judge, completeness estimated by capture–recapture.",
  collection: "documentation",
  status: "final",
)

// Every headline number is interpolated from the committed record, never hand-typed:
// a re-run of the search regenerates artifacts/data/ar016/ and this article follows.
#let n = json("/artifacts/data/ar016/numbers.json")
#let refs = json("/artifacts/data/ar016/references.json")
#let ms = n.estimates.chapman_memory_x_search
#let tlo = n.honest_readout.true_size_range.at(0)
#let thi = n.honest_readout.true_size_range.at(1)
#let rlo = n.honest_readout.recall_range_pct.at(0)
#let rhi = n.honest_readout.recall_range_pct.at(1)
#let yc = n.yield_curve
#let pv = n.provenance
#let fn = n.funnel
#let ax = n.axis_distribution
#let cv = json("/artifacts/data/ar016/corpus_view.json")

// function-axis display order + human labels
#let axis-order = (
  ("communication-coherence-routing", "Communication-through-coherence, routing & gating"),
  ("attention-selection", "Attention & stimulus selection"),
  ("stimulus-competition", "Stimulus & biased competition"),
  ("coincidence-gain-window", "Coincidence detection, gain & the temporal window"),
  ("phase-coding-timing", "Phase coding & spike timing"),
  ("binding-synchrony", "Binding by synchrony"),
  ("causal-optogenetic-performance", "Causal / optogenetic PV–gamma & circuit performance"),
  ("mechanism-review", "Reviews & theory (mechanism → function)"),
)

#let body = [
  This article is a *corpus*, not a review. It is the exhaustive, auditable paper list for one narrow question — the map — with the synthesis, the open debates, and the gaps left for a later pass. The question: *in which papers is the PING mechanism explicitly the vehicle for a functional claim?* PING here means gamma generated by the reciprocal pyramidal↔interneuron loop with its characteristic excitatory–inhibitory timing; a paper is in the corpus only if it both invokes that mechanism as the generator of the rhythm *and* argues that a cognitive or computational function follows from it — attention, stimulus selection, communication-through-coherence, gain control and coincidence windows, phase coding, or binding. Papers where gamma merely *correlates* with a function, or where the mechanism is studied with no functional claim, are out. The scope was frozen and tagged (`freeze-ar016-v1`) before any measured run, so the recall number below is valid — both samples target the same fixed population.

  == Confidence header

  #table(
    columns: (auto, auto),
    align: (left, left),
    stroke: 0.5pt + luma(200),
    [*Papers in the corpus*], [#n.corpus_in_hand, every DOI verified],
    [*Estimated true size*], [≈ #tlo–#thi (two-source Chapman #ms.N, 95% CI #ms.ci95.at(0)–#ms.ci95.at(1))],
    [*Estimated recall*], [≈ #rlo–#rhi %],
    [*Channels*], [memory · keyword-search · citation-graph · embedding],
    [*Membership authority*], [one two-stage judge (wide-net → confirm), consistent across channels],
    [*Coverage caveats*], [keyless (no Semantic Scholar / PubMed); single judge per paper; OpenAlex abstract gaps on seminal papers],
  )

  The estimate is a *range, not a point*, and that is deliberate. The three pairwise capture–recapture estimates disagree — #n.estimates.chapman_memory_x_search.N, #n.estimates.chapman_search_x_citation.N, and #n.estimates.chapman_memory_x_citation.N — and that disagreement is diagnostic, not noise: the channels have heterogeneous catchability (memory reaches the old and seminal, search the recent and well-indexed), which violates the independence the estimator assumes. No single $hat(N)$ is trustworthy, so the honest output is the band #tlo–#thi and a recall of #rlo–#rhi %.

  == Method — four decorrelated channels, one judge

  The premise is a division of labour. The model is a good *size oracle* and a good *membership judge* but a bad *recall oracle* — it can tell hundreds from thousands, and can judge whether a specific paper is in scope, but it cannot list the hundreds without fabricating. So recall is supplied by databases and the citation graph, membership is decided by judgment, and every candidate DOI is verified against Crossref before it is allowed in — an unresolvable DOI is treated as a hallucination and discarded.

  Recall was gathered from four channels chosen to be *orthogonal* — to fail on different papers, so their union covers what any one misses:

  - *Memory* — 20 decorrelated elicitation passes (per-lab, per-function-axis, per-decade), each in its own context, unioned. Owns the old, seminal, abstract-less stratum.
  - *Keyword search* — a deep OpenAlex full-text sweep across the frozen synonym ring, deliberately high-recall. Owns the recent, well-indexed stratum.
  - *Citation graph* — the backward references and forward citers of the found set, scored by how many of the corpus each candidate connects to. Owns the well-connected stratum, independent of words and of memory.
  - *Embedding* — SPECTER nearest-neighbours (Semantic Scholar) of the strongest seeds, independent of shared words, citations, and authorship.

  Membership was *not* decided by any keyword filter — an earlier attempt to do so failed, because a filter strict enough to exclude the broad "gamma and attention" literature also excludes the function-forward canonical papers whose abstracts never say "interneuron". Instead every candidate from every channel was passed through one consistent two-stage judge — a wide-net first pass, then a strict confirming pass against the frozen rubric — so the in/out boundary is one authority applied uniformly. Completeness was then estimated by Lincoln–Petersen / Chapman capture–recapture over that single judged population, treating each channel as an independent capture.

  == Results — funnel, provenance, saturation

  The four channels surfaced #fn.distinct_papers_judged distinct candidate papers, every one put through the same membership judge. #fn.accepted_in_scope survived; #fn.rejected were rejected — an acceptance rate of #fn.acceptance_pct %. That selectivity is the scope doing its work: most candidates are gamma-and-cognition papers that never make the mechanism-*carries*-function argument, and the judge holds the line.

  #table(
    columns: (auto, auto),
    align: (left, right),
    stroke: 0.5pt + luma(200),
    [*Candidates judged (search + memory union)*], [#fn.by_stage.search_plus_memory_union],
    [*Candidates judged (citation graph)*], [#fn.by_stage.citation_candidates],
    [*Candidates judged (embedding)*], [#fn.by_stage.embedding_candidates],
    [*Total distinct papers judged*], [#fn.distinct_papers_judged],
    [*Accepted into the corpus*], [#fn.accepted_in_scope (#fn.acceptance_pct %)],
    [*Rejected*], [#fn.rejected],
  )

  The corpus is genuinely the union of complementary channels; no single one would have built it:

  #table(
    columns: (auto, auto),
    align: (left, right),
    stroke: 0.5pt + luma(200),
    [*Found by memory only*], [#pv.memory_only],
    [*Found by search only*], [#pv.search_only],
    [*Found by memory and search*], [#pv.memory_and_search],
    [*Found by citation graph only*], [#pv.citation_only],
    [*Total*], [#n.corpus_in_hand],
  )

  Only #pv.memory_and_search of the #n.corpus_in_hand papers were caught by both memory and keyword search — the low overlap is real channel complementarity, and it is *why* it took four channels rather than one.

  The stopping decision rests on the marginal-yield curve, not on hitting a target. Each successive channel returned fewer new in-scope papers:

  #table(
    columns: (auto, auto, auto),
    align: (left, right, right),
    stroke: 0.5pt + luma(200),
    [*Channel*], [*New in-scope*], [*Candidates screened*],
    [memory], [#yc.memory], [—],
    [keyword search], [+#yc.search_new], [1552],
    [citation graph], [+#yc.citation_new], [1154],
    [embedding (SPECTER)], [+#yc.embedding_new], [263],
  )

  The yield collapsed from #yc.memory to +#yc.search_new to +#yc.citation_new to +#yc.embedding_new. The final channel — orthogonal, abstract-rich, centred on the hundred strongest seeds — screened 263 semantic neighbours and added nothing. That is the saturation signal: not a proof (nothing here is), but the convergent kind — falling returns together with an orthogonal null. The result is discounted only slightly, because SPECTER's recommendations are recency-biased and so its null speaks most strongly for the recent stratum; but the old stratum was already swept by the citation channel, so between the two the un-caught in-scope region looks small.

  == The corpus by function axis

  Every paper is tagged with the one function its mechanism-to-function argument chiefly serves, from a fixed set of eight. The distribution is the first-order map of the field:

  #table(
    columns: (auto, auto),
    align: (left, right),
    stroke: 0.5pt + luma(200),
    ..axis-order.map(((k, label)) => (label, [#ax.at(k, default: 0)])).flatten(),
    [*Total*], [#n.corpus_in_hand],
  )

  Communication-through-coherence and routing is the largest single axis (#ax.at("communication-coherence-routing", default: 0)) — the field's centre of gravity is the claim that the E–I gamma rhythm gates *which* signals pass between areas. The causal / optogenetic cluster (#ax.at("causal-optogenetic-performance", default: 0)) is now a first-class axis in its own right, marking the shift from "gamma correlates with function" to "drive the PV cells and watch function change". The full annotated list, grouped by axis with a one-line rationale per paper, is the bibliography below.

  == Discussion — what the number means and does not

  What can be claimed: this is a DOI-verified corpus of #n.corpus_in_hand papers, with a *measured* — not assumed — recall of roughly #rlo–#rhi %, and a documented reason for every paper's inclusion. What cannot: that it is complete. The tail of a semantic corpus goes asymptotic — papers in no index, mis-tagged, or truly obscure cost more per paper than the bulk did, and the capture–recapture band (#tlo–#thi) is itself uncertain because the channels are heterogeneous. A notable structural fact surfaced along the way: the most-cited *references* of this corpus are foundational papers that are purely mechanism (how gamma is generated) or purely function (that attention modulates gamma) — each satisfies only half the "mechanism *carries* function" test, which is why the citation graph flooded us with candidates but converted few. The scope boundary is genuinely restrictive; the intersection is the interesting, and smaller, set.

  == Next steps

  The corpus is the input to the review, not the review. The obvious continuations: (1) a second, independent judge pass to turn the single-judge boundary into a voted one and tighten precision; (2) one more orthogonal recall channel where a key exists — PubMed for the biomedical silo, or author-complete feeds for the core labs — expected, from the yield curve, to add only single digits; (3) the synthesis itself — reading down each axis below to map which mechanistic claims are contested and where the gaps are. Scope reopens only under a new freeze tag; questions that surfaced during the build are logged, not silently acted on.

  == The corpus — annotated bibliography by function axis

  All #n.corpus_in_hand papers, grouped by primary function axis and sorted by year, each with a one-sentence statement of how the E–I/PING gamma mechanism carries its functional claim and a tag for the channel that found it (_m_ memory · _s_ search · _m+s_ both · _c_ citation).

  #let bib-css = "
    .cb-entry{margin:0 0 .85rem 0;line-height:1.55;}
    .cb-entry .byl{font-weight:650;}
    .cb-entry em{font-style:italic;}
    .cb-doi{color:var(--muted);text-decoration:none;font-size:.88em;margin-left:.25em;}
    .cb-doi:hover{text-decoration:underline;color:var(--ink);}
    .cb-why{font-size:var(--fs-small);color:var(--muted);margin:.2rem 0 0 1.4rem;line-height:1.5;}
    .cb-chan{display:inline-block;font-size:.72em;letter-spacing:.03em;color:var(--muted);border:1px solid currentColor;border-radius:3px;padding:0 .35em;margin-left:.45em;opacity:.6;vertical-align:.08em;}
  "
  #context {
    let web = target() == "html"
    if web { html.elem("style", bib-css) }
    for (key, label) in axis-order {
      let items = cv.filter(r => r.axis == key)
      heading(level: 3, label + " (" + str(items.len()) + ")")
      for r in items {
        if web {
          html.elem("div", attrs: (class: "cb-entry"), {
            html.elem("span", attrs: (class: "byl"), r.byline)
            ". " + r.title + ". "
            if r.venue != "" { html.elem("em", r.venue); ". " }
            html.elem("a", attrs: (class: "cb-doi", href: "https://doi.org/" + r.doi, target: "_blank", rel: "noopener"), "doi:" + r.doi)
            html.elem("div", attrs: (class: "cb-why"), {
              r.rationale
              html.elem("span", attrs: (class: "cb-chan"), r.channel)
            })
          })
        } else {
          block(below: 0.9em, {
            strong(r.byline); ". "; r.title; ". "
            if r.venue != "" { emph(r.venue); ". " }
            text(fill: luma(110), size: 0.9em)[doi:#r.doi]
            linebreak()
            pad(left: 1.2em, text(size: 0.9em, fill: luma(100))[#r.rationale #h(0.3em) #box(stroke: 0.5pt + luma(180), inset: (x: 0.35em), radius: 2pt)[#text(size: 0.85em)[#r.channel]]])
          })
        }
      }
    }
  }
]
