#import "/demolab-engine/build/lib.typ": numbers-table, provenance-footer

#let meta = (
  title: "PING-AI state comparison",
  date: "2026-06-09",
  description: "One COBANet runs as gamma PING or the Vreeswijk-Sompolinsky asynchronous-irregular state; the single control is the cross-cell correlation of the input.",
  collection: "miscellaneous",
  status: "revising",
)

#let run = json("/artifacts/data/exp050/numbers.json")

#let body = [
  == Abstract

  One network (#link("/ar003/")[COBANet]) can run as the gamma rhythm *PING* or as the #link("https://doi.org/10.1126/science.274.5293.1724")[Vreeswijk-Sompolinsky] *asynchronous-irregular* state. With everything else harmonised — connectivity, weights, $W^(I I)$ — the two differ in a single control: the *correlation of the input* across cells. Shared (correlated) drive gives gamma; per-cell independent drive gives the balanced state.

  == Methods

  === Model parameters

  The two models are identical COBANet except for the input. The table is the full configuration; the only rows that differ — all of them describing the input — are in _italics_.

  #table(
    columns: 3,
    [Parameter], [PING], [V&S AI],
    [Model], [COBANet (conductance LIF)], [COBANet (conductance LIF)],
    [$N_E$ / $N_I$], [1024 / 256], [1024 / 256],
    [$Delta t$ / $T$], [0.25 ms / 1000 ms], [0.25 ms / 1000 ms],
    [$tau_E$ / $tau_I$ (AMPA / GABA)], [2 / 9 ms], [2 / 9 ms],
    [Recurrent connectivity], [sparse fixed-fan-in, $p = 0.2$], [sparse fixed-fan-in, $p = 0.2$],
    [$W^(E I)$ (E→I)], [$cal(N)(0.6, 0.18)$ μS], [$cal(N)(0.6, 0.18)$ μS],
    [$W^(I E)$ (I→E)], [$cal(N)(3.0, 0.9)$ μS], [$cal(N)(3.0, 0.9)$ μS],
    [$W^(I I)$ (I→I)], [none], [none],
    [External drive], [_dense $W_"in"$ (shared 1024-neuron layer)_], [_diagonal $W_"in"$ (one private input per cell)_],
    [Drive rate], [_45 Hz (E)_], [_45 Hz (E), 8 Hz (I)_],
    [Input correlation across cells], [_correlated_], [_independent_],
  )

  Both models use sparse fixed-fan-in recurrent connectivity at $p = 1 - s = 0.2$ on the E↔I matrices ($W^(E E) = 0$, $W^(I I)$ off). Because $p$ is also the fraction of recurrent input any two cells share ($⟨ n_"shared" ⟩ \/ K = K \/ N = p$), it sets how strongly the loop can cohere — connectivity is the _internal_ counterpart of the input knob. We fix it at a cortically realistic $p = 0.2$ (local E↔I connectivity runs ≈ 0.1–0.5) — dense enough for the recurrent loop to cohere, so connectivity is shared and does not distinguish the regimes.

  === Model differences

  The models share everything above — connectivity, the E↔I weights, $W^(I I)$. The single difference is the *input*: a shared (correlated) drive for PING, per-cell independent (uncorrelated) drive for the V&S cell.

  Both deliver 45 Hz Poisson through the _same_ input pathway — spikes routed by $W_"in"$ into a decaying AMPA conductance. The only difference is the *structure of $W_"in"$*. The external excitatory conductance onto E cell $j$ obeys

  $ tau_E dot(g)_j^"ext" (t) = - g_j^"ext" (t) + sum_k W_(j k)^"in" s_k (t), quad W^"in" = cases("dense" & "(PING)", g_0 bb(1) med "(diagonal)" & "(V&S AI)") $

  where:

  - $g_j^"ext" (t)$ — external excitatory conductance onto E cell $j$;
  - $tau_E$ — AMPA decay time constant (2 ms), common to both;
  - $s_k (t) = sum_m delta(t - t_k^m)$ — spike train of input neuron $k$ (Poisson, 45 Hz); $N_"in" = 1024$;
  - $W^"in"$ — input weight matrix: *dense* for PING (every E cell reads the whole input layer, so all cells share the same drive) or *diagonal* $g_0 bb(1)$ for the V&S cell (each E cell reads only its own input neuron, $W_(j k)^"in" = g_0 delta_(j k)$, so the drives are independent);
  - $g_0$ — per-spike conductance, 0.38 μS (the diagonal weight).

  A dense $W_"in"$ correlates the input across cells; a diagonal $W_"in"$ leaves it independent. (In the runner the diagonal case is realized as a per-cell independent conductance rather than a literal identity matrix — the two are equivalent.)

  The consequence is the cross-cell correlation of the drive:

  $ "Corr"(g_j^"ext", g_(j')^"ext") > 0 quad "(PING, shared layer)", quad "Corr"(g_j^"ext", g_(j')^"ext") = 0 quad "(V&S AI, private streams)", quad j eq.not j'. $

  The shared layer is a _common reference_ the loop can lock onto; the private streams kick each cell independently, with no common phase. Both drive E at the same 45 Hz, so rate is not the difference. What both share: neither input carries any rhythm. Both are featureless, steady Poisson (Figure 1), so PING's gamma is generated by the network, not inherited from the drive.

  == Results

  #figure(
    image("/artifacts/data/exp050/input_compare.png", width: 100%),
    caption: [Top: a 300 ms raster of the drive — PING's shared input layer (left) and the V&S cell's per-cell private streams (right), both 45 Hz. Bottom: the population rate of each drive. Both are featureless, steady Poisson at the same rate; the input carries no oscillation in either regime. The regimes differ only in _correlation structure_ — shared layer vs private streams — not in rate or temporal content.],
  )

  #figure(
    image("/artifacts/data/exp050/raster_compare.png", width: 100%),
    caption: [Row 1 is the raster with both populations on one axis — E (black) below, I (red) above the divider — so the I-leads-E gamma timing is visible directly. Both networks have identical wiring (sparse $p = 0.2$, matched weights, no $W^(I I)$); only the input differs. Left, PING (shared input): cycle-locked gamma bursts, a sharp 32 Hz peak, regular (sub-Poisson) ISIs (CV 0.64), cross-correlations combing at the gamma period (peak 0.063). Right, V&S AI (independent input): scattered raster, broadband spectrum, irregular ISIs, flat cross-correlation (peak 0.010). Same network and wiring, opposite dynamics — the input correlation alone.],
  )

  == Next steps

  The two regimes are now identical except for the input — same connectivity, weights, and 45 Hz E-drive rate — and the difference is its *cross-cell correlation*: a shared input layer (PING) versus per-cell independent streams (V&S). (One residual asymmetry: the V&S cell drives its I pool with an independent 8 Hz stream to decorrelate it, where PING's I is loop-driven.) Turning correlation into a single, continuous control is the remaining work.

  *A faithful correlation knob.* The tidy idea — mix a shared common stream with private streams and dial the shared fraction $c in [0, 1]$ — breaks at the $c = 1$ extreme if "shared" is _one_ stream broadcast verbatim: every cell then receives identical input and locks into trivial synchrony (cross-correlation ≈ 0.99, a broad ≈ 74 Hz peak) rather than loop-generated gamma. Real correlated drive is a shared _population_, not one identical signal. The fix is a shared _layer_ of $K_"shared"$ common input neurons (each cell reading all of them), interpolated against private streams at matched rate — correlated without being identical, so genuine gamma survives. With that knob, the gamma↔asynchronous boundary can be mapped continuously over $c$.
]
