#import "templates/article-layout.typ": journal-article
#import "templates/result-card.typ": journal-result-card, with-result-sections, result-figure-ref, result-card
#import "templates/methods.typ": journal-methods, method-card
#import "templates/parameters-table.typ": parameters-table
#import "templates/references.typ": journal-references
#import "/.demolab/lib.typ": data-image, cite
#import "templates/dataset.typ": video, data-file, inputs-ready, pending-report, run-view, input-assets
#import "templates/abstract.typ": journal-abstract
#let data-file = data-file.with(article: "exp099")

#let meta = (
  tags: ("data", "v36.0.0"),
  // Author-locked title: do not change.
  title: "Susin and Destexhe (2021)",
  created_at: "2026-08-26T00:00:00Z",
  updated_at: "2026-09-09",
  description: "Independent excitatory afferent drive strengthens population bursting in a calibrated conductance-based E/I network.",
  collection: "demo",
  order: 13,
)

#let inputs = ("exp099",)

#let render-report(data-file) = [
  #journal-abstract(
    question: [We tested whether increased nonrhythmic afferent excitation recruits collective oscillations in a modified replication of Susin and Destexhe’s (2021) PING network.],
    approach: [We searched afferent rates and recurrent weights in a smaller conductance-based LIF network for weak baseline correlations and stimulus-dependent bursting.],
    finding: [Increased excitation onto both populations strengthened bursting in the selected simulation.],
    scope: [This single-seed exploratory search characterizes one selected configuration.],
  )

  == Introduction

  In the pyramidal–interneuron gamma (PING) network of Susin and Destexhe (2021), increasing nonrhythmic excitatory Poisson drive onto both populations shifted an asynchronous-irregular-like baseline toward stronger gamma oscillations generated by recurrent E/I interactions.#cite(1)

  We attempted a modified replication, retaining the reference synaptic decay times, delays and stimulus timing while searching afferent rates and recurrent weights for weak baseline correlations and stimulus-dependent bursting.

  Our 2,000-neuron network is smaller and denser but gives each neuron fewer recurrent inputs. Non-adapting LIF neurons replace AdEx neurons; afferent rates and recurrent excitation are lower; inputs are independent across targets; and a 500 ms hidden baseline precedes the display. These changes limit quantitative alignment in firing rates, burst structure or timing.

  == Results

  #with-result-sections[

    #journal-result-card(
      title: "Implemented circuit architecture",
      orientation: [The circuit contains 1,600 excitatory and 400 inhibitory neurons with recurrent AMPA and GABA synapses (#result-figure-ref(<fig:exp099-network>)). Each neuron receives independent excitatory Poisson input; recurrent I neurons provide inhibition.],
      visual: [
        #figure(
          data-image(
            data-file("exp099/network.svg"),
            width: 100%,
            alt: "Structural diagram of 1,600 excitatory and 400 inhibitory neurons with independent private excitatory afferents and recurrent AMPA and GABA projections.",
          ),
          caption: [Structural schematic of the implemented populations, recurrent AMPA and GABA projections, and private excitatory afferents. Rates are per afferent source; weights are conductance increments per event.],
          kind: image,
          supplement: [Figure],
        ) <fig:exp099-network>
      ],

    )

    #let private-clip = data-file("exp099/private-e-drive.mp4")
    #if private-clip != none { let _ = read(private-clip, encoding: none) }
    #journal-result-card(
      title: "Private drive strengthens bursting",
      observation: [In the selected configuration, a 50% increase in E- and I-targeted afferent rates strengthened population bursting (#result-figure-ref(<fig:exp099-private>)). Mean E/I firing rates rose from 3.53/3.83 Hz at baseline to 11.51/11.93 Hz during the plateau and were 4.28/4.38 Hz in recovery. Mean E spike-count correlation rose from 0.009 to 0.267.],
      visual: [
        #figure(
          video(private-clip),
          caption: [Seed-7 simulation played over 25 seconds; displayed time 0–600 ms follows a hidden 500 ms baseline. E- and I-targeted afferent rates rose from 0.8 to 1.2 Hz over 200–250 ms, held to 350 ms, then returned by 400 ms. A: sampled neurons, connections and target-specific aggregate input streams. B: population mean voltages and conductances onto E. C: their 40 ms trail. D: per-neuron rates averaged over the trailing 20 ms. E: prescribed per-source input rates. F: fixed nonzero recurrent weights.],
          kind: image,
          supplement: [Figure],
        ) <fig:exp099-private>
      ],

    )

    #journal-result-card(
      title: "E and I bursts overlap in time",
      notes: [
        - Direct external excitation of I may contribute to the overlapping E/I bursts. In an earlier diagnostic using the previous calibration without external I excitation, I peaks followed E peaks by approximately 1 ms across nine plateau bursts.
        - An earlier 1.5-second protocol produced a PING-like burst around 280 ms, before the 500 ms input ramp. Susin and Destexhe likewise report fluctuation-driven spontaneous gamma bursts and residual baseline oscillations.#cite(1)
      ],
      observation: [Excitatory and inhibitory neurons formed aligned bursts during increased drive (#result-figure-ref(<fig:exp099-raster>, panel: "B")). Their plateau spike-count profiles overlap strongly but vary in amplitude and timing (#result-figure-ref(<fig:exp099-raster>, panel: "C–D")); narrow burst bands alternate with dispersed spikes.],
      visual: [
        #figure(
          data-image(
            data-file("exp099/spike-raster.png"),
            width: 100%,
            alt: "Four-panel plot showing afferent rates, all E and I spikes over 600 ms, a 250–350 ms raster close-up, and unsmoothed population spike counts in 1 ms bins.",
          ),
          caption: [Spike timing in the seed-7 simulation from #result-figure-ref(<fig:exp099-private>), after the hidden 500 ms baseline. A: coincident E- and I-targeted rates (black solid and red dashed). B: all spikes from 1,600 E neurons (black, lower) and 400 I neurons (red, upper); dotted lines mark the pulse and shading the close-up. C: the 250–350 ms plateau window. D: unsmoothed population-total counts in 1 ms bins over that window; E contains four times as many neurons as I.],
          kind: image,
          supplement: [Figure],
        ) <fig:exp099-raster>
      ],
    )

    #result-card[
      === Reference PING network

        #figure(
          data-image(
            data-file("exp099/susin-destexhe-2021-ping.png"),
            width: 55%,
            alt: "Published PING column from Susin and Destexhe Figure 4, showing panels B and C: external Poisson drive and the spike raster.",
          ),
          caption: [Cropped from Figure 4 (left PING column, panels B and C) of Susin and Destexhe (2021).#cite(1) © 2021 Susin and Destexhe; reproduced under #link("https://creativecommons.org/licenses/by/4.0/")[CC BY 4.0]. B shows external Poisson drive; C shows the spike raster. Original panel labels and colours are retained.],
          kind: image,
          supplement: [Figure],
        ) <fig:exp099-reference>

        The networks share a drive-dependent response but differ in three respects:

        - Increased E/I excitation strengthens collective activity in both; ours has sharper burst bands (#result-figure-ref(<fig:exp099-reference>, panel: "B–C"); #result-figure-ref(<fig:exp099-raster>, panel: "A–B")).
        - Their raster samples 1,000 E and 1,000 I neurons from 25,000; ours shows all 1,600 E and 400 I neurons.
        - Both show 600 ms with a 200 ms pulse. Their drive is 2→3→2 Hz during ongoing activity; ours is 0.8→1.2→0.8 Hz after a hidden 500 ms baseline.

        Sharper bursts may reflect our non-adapting LIF neurons, altered thresholds and refractory periods, fewer recurrent inputs, recalibrated weights or lower background drive (@tab:exp099-parameters); sampling also affects raster density. Controlled comparisons are needed.

    ]

  ]

  #journal-methods(body: (
    method-card([Construct the modified replication], [We replaced the adapting AdEx neurons in the PING network of Susin and Destexhe (2021)#cite(1) with 1,600 excitatory and 400 inhibitory conductance-based LIF neurons. Recurrent connections, including possible self-connections, were sampled independently with 10% probability. @tab:exp099-parameters compares the models. We used a 0.1 ms timestep.]),
    method-card([Apply the input protocol], [Each neuron received 400 equivalent independent excitatory Poisson afferents, each adding 4 nS of AMPA conductance. We initialized voltages at −65 mV, simulated a 500 ms hidden baseline, then preserved state through the 600 ms display. From displayed time 200 ms, both populations received a 50% rate increase with a 50 ms rise, 100 ms plateau and 50 ms fall (#result-figure-ref(<fig:exp099-private>, panel: "E")).]),
    method-card([Search input and recurrent strengths], [We tested the 27 combinations of baseline afferent rate {0.4, 0.6, 0.8} Hz, recurrent excitatory weight {1.0, 1.25, 1.5} nS and inhibitory weight {2.7, 3.34, 4.0} nS. All combinations used seed 7 and the same recurrent connectivity; those at each input rate shared afferent spike trains.]),
    method-card([Measure population activity], [We measured per-neuron firing rates during baseline (0–200 ms), plateau (250–350 ms) and recovery (400–600 ms). Synchrony was the mean pairwise Pearson correlation of 10 ms spike counts among up to 100 evenly sampled neurons per population with nonzero count variance. We calculated median interspike-interval coefficient of variation (CV) among neurons producing at least five spikes, retaining the eligible-neuron count.]),
    method-card([Measure burst concentration], [During the 200 ms pulse in each search run, we detected peaks in E-population firing rates using 1 ms bins, Gaussian smoothing with σ = 1 ms, minimum separation of 8 ms, and prominence exceeding the larger of 5 Hz or 20% of the smoothed rate range. Burst participation was the median fraction of E neurons firing within 10 ms windows centred on these peaks.]),
    method-card([Select the configuration], [We jointly inspected rasters, rates, correlations and burst participation. We selected 0.8 Hz baseline drive, 1.0 nS recurrent excitation and 3.34 nS recurrent inhibition for weak baseline correlations with clear stimulus-dependent bursting. Selection was exploratory and seed-specific.]),
  ))

  #parameters-table(
    ([Variable], [Their value], [Our value], [Difference and why]),
    (
      ([Neurons E / I], [20,000 / 5,000], [1,600 / 400], [Smaller network; same ratio.]),
      ([Recurrent connection probability], [2%], [10%], [Partly offsets fewer neurons.]),
      ([Mean recurrent inputs E / I], [400 / 100], [160 / 40], [Fewer inputs in the smaller network.]),
      ([Neuron model], [Adaptive exponential (AdEx); adapting E], [Conductance LIF; no adaptation], [Simpler membrane dynamics.]),
      ([Capacitance], [150 pF], [150 pF], [Matched.]),
      ([Leak conductance], [10 nS], [10 nS], [Matched; membrane time constant 15 ms.]),
      ([Rest / reset voltage], [−65 mV], [−65 mV], [Matched.]),
      ([Threshold E / I], [−40 / −47.5 mV; effective AdEx threshold], [−50 / −50 mV; hard threshold], [Different model-specific threshold definitions.]),
      ([Refractory period E / I], [5 / 5 ms], [3 / 1.5 ms], [Retained existing LIF settings.]),
      ([AMPA / GABA decay], [1.5 / 7.5 ms], [1.5 / 7.5 ms], [Matched.]),
      ([Synaptic delay], [1.5 ms], [1.5 ms], [Matched.]),
      ([Timestep], [0.1 ms], [0.1 ms], [Matched.]),
      ([External afferents per neuron], [400 on average; some shared sources], [400 equivalent independent sources], [Independent target-specific input streams.]),
      ([Baseline source rate E / I], [2 / 2 Hz], [0.8 / 0.8 Hz], [Selected for weak baseline correlations and stimulus-dependent bursting.]),
      ([Increased drive], [3 / 3 Hz condition], [1.2 / 1.2 Hz], [Both populations receive a 50% increase, matching the reference stimulation pattern.]),
      ([External excitatory weight], [4 nS], [4 nS], [Matched.]),
      ([Recurrent excitatory weight], [5 nS], [1.0 nS], [Selected jointly with afferent rate and inhibitory weight.]),
      ([Recurrent inhibitory weight], [3.34 nS], [3.34 nS], [Matched; stronger relative to recurrent excitation.]),
      ([Separate external GABA], [None], [None], [Inhibition comes from recurrent I neurons.]),
    ),
    columns: (1.1fr, 1fr, 1fr, 1.5fr),
    table-label: <tab:exp099-parameters>,
    caption: [Reference PING settings from Susin and Destexhe (2021)#cite(1) and our calibrated conductance-based LIF settings. Paired values are E / I; recurrent input counts are expectations. Weights are conductance increments per presynaptic event and external rates are per afferent source. AdEx thresholds are effective; LIF thresholds are hard.],
  )

  #run-view("exp099", inputs)

  #journal-references((
    (text: [E. Susin and A. Destexhe. “Integration, coincidence detection and resonance in networks of spiking neurons expressing Gamma oscillations and asynchronous states.” _PLOS Computational Biology_ 17(9), e1009416 (2021).], doi: "10.1371/journal.pcbi.1009416"),
  ))
]

#let report-body = if inputs-ready(data-file, inputs) {
  render-report(data-file)
} else {
  pending-report(data-file, inputs, [], ())
}

#let meta = meta + (assets: input-assets("exp099", inputs))
#let body = journal-article("exp099", inputs, report-body, dataset-placed: inputs-ready(data-file, inputs))
